<?php
require './Fonctions.php'; // Inclusion du fichier de connexion à la base de données
$pdo = connexion();
    $sql = "INSERT INTO film (title, synopsis, studio) VALUES

('Le Rêve céleste', 'Une guerre imminente cherche la vérité.', 'Cinéstorm'),
('Un Trésor de l’oubli', 'Un mystère inexpliqué affronte ses peurs.', 'Star Studios'),
('Vers Rêve interdit', 'Une guerre imminente défie les lois de la réalité.', 'Émotion Pictures'),
('Les Dernier du désert', 'Une guerre imminente réveille une légende ancienne.', 'Cinéstorm'),
('Vers Dernier mystérieux', 'Un héros solitaire défie les lois de la réalité.', 'Star Studios'),
('Sur Ombre fantôme', 'Un mystère inexpliqué se bat contre une force obscure.', 'Star Studios'),
('Sous Voyage mystérieux', 'Une guerre imminente affronte ses peurs.', 'Émotion Pictures'),
('Les Voyage mystérieux', 'Un voyage temporel affronte ses peurs.', 'Dreamlight'),
('Une Choc céleste', 'Un scientifique fou doit sauver le monde.', 'Mythic Entertainment'),
('La Voyage de l’oubli', 'Un héros solitaire se bat contre une force obscure.', 'Darkline Studios'),
('La Cri éternel', 'Un mystère inexpliqué se bat contre une force obscure.', 'Émotion Pictures'),
('Une Trésor mystérieux', 'Un robot en fuite découvre un secret enfoui.', 'Darkline Studios'),
('Vers Secret mystérieux', 'Un robot en fuite cherche la vérité.', 'LoveFilm Productions'),
('Un Trésor des Abysses', 'Une guerre imminente se bat contre une force obscure.', 'Studio du Rire'),
('Sur Ombre de glace', 'Une équipe improbable se bat contre une force obscure.', 'Dreamlight'),
('Au-delà Éclat du Temps', 'Une ancienne prophétie doit sauver le monde.', 'Flashbox Films'),
('Au-delà Secret du Temps', 'Un scientifique fou défie les lois de la réalité.', 'Mythic Entertainment'),
('Sous Éclat du désert', 'Un voyage temporel tente de changer le destin.', 'Studio du Rire'),
('Au-delà Voyage de l’oubli', 'Une guerre imminente doit sauver le monde.', 'Star Studios'),
('Au-delà Ombre éternel', 'Un voyage temporel tente de changer le destin.', 'Studio du Rire'),
('La Cri fantôme', 'Une jeune fille curieuse affronte ses peurs.', 'Star Studios'),
('Les Souffle de l’oubli', 'Une ancienne prophétie se bat contre une force obscure.', 'Nova Films'),
('Vers Souffle de glace', 'Un scientifique fou réveille une légende ancienne.', 'Émotion Pictures'),
('Le Cri de l’oubli', 'Un héros solitaire remonte le temps.', 'Cinéstorm'),
('Dans Dernier éternel', 'Un voyage temporel défie les lois de la réalité.', 'Flashbox Films'),
('Au-delà Cri du désert', 'Un robot en fuite explore l’inconnu.', 'LoveFilm Productions'),
('Dans Rêve du Temps', 'Un robot en fuite affronte ses peurs.', 'Nova Films'),
('Une Secret interdit', 'Une équipe improbable découvre un secret enfoui.', 'Nova Films'),
('Dans Ombre de l’oubli', 'Un héros solitaire défie les lois de la réalité.', 'Nova Films'),
('Vers Cri fantôme', 'Un robot en fuite explore l’inconnu.', 'Studio du Rire'),
('Sous Souffle fantôme', 'Une guerre imminente défie les lois de la réalité.', 'Darkline Studios'),
('Sous Secret du désert', 'Une jeune fille curieuse doit sauver le monde.', 'Dreamlight'),
('Les Secret interdit', 'Une ancienne prophétie tente de changer le destin.', 'LoveFilm Productions'),
('Sous Rêve mystérieux', 'Un mystère inexpliqué affronte ses peurs.', 'Cinéstorm'),
('Une Choc mystérieux', 'Un voyage temporel doit sauver le monde.', 'Studio du Rire'),
('Les Trésor des Abysses', 'Une équipe improbable doit sauver le monde.', 'Émotion Pictures'),
('Vers Rêve des Abysses', 'Un scientifique fou affronte ses peurs.', 'Cinéstorm'),
('Les Dernier céleste', 'Un voyage temporel remonte le temps.', 'Studio du Rire'),
('Une Voyage interdit', 'Une guerre imminente découvre un secret enfoui.', 'Studio du Rire'),
('Une Secret interdit', 'Un détective tourmenté cherche la vérité.', 'Studio du Rire'),
('La Cri céleste', 'Une guerre imminente affronte ses peurs.', 'Mythic Entertainment'),
('Vers Éclat céleste', 'Un voyage temporel défie les lois de la réalité.', 'Darkline Studios'),
('Le Rêve interdit', 'Une guerre imminente se bat contre une force obscure.', 'Émotion Pictures'),
('Un Cri du Temps', 'Une guerre imminente cherche la vérité.', 'Studio du Rire'),
('Un Trésor céleste', 'Un scientifique fou tente de changer le destin.', 'LoveFilm Productions'),
('Une Souffle du Temps', 'Un voyage temporel affronte ses peurs.', 'Studio du Rire'),
('La Choc de glace', 'Une guerre imminente affronte ses peurs.', 'LoveFilm Productions'),
('Sur Voyage interdit', 'Un robot en fuite affronte ses peurs.', 'Mythic Entertainment'),
('Dans Souffle du désert', 'Un robot en fuite défie les lois de la réalité.', 'Darkline Studios'),
('Sous Dernier fantôme', 'Un robot en fuite explore l’inconnu.', 'Studio du Rire'),
('Dans Dernier de glace', 'Une équipe improbable défie les lois de la réalité.', 'Nova Films'),
('Les Cri éternel', 'Une équipe improbable remonte le temps.', 'Star Studios'),
('Sur Secret fantôme', 'Un mystère inexpliqué défie les lois de la réalité.', 'Mythic Entertainment'),
('Une Rêve du désert', 'Une ancienne prophétie remonte le temps.', 'Flashbox Films'),
('Au-delà Secret mystérieux', 'Une jeune fille curieuse affronte ses peurs.', 'Émotion Pictures'),
('Dans Ombre interdit', 'Un détective tourmenté se bat contre une force obscure.', 'Mythic Entertainment'),
('Au-delà Dernier céleste', 'Une ancienne prophétie se bat contre une force obscure.', 'Flashbox Films'),
('Sous Souffle de glace', 'Une jeune fille curieuse remonte le temps.', 'LoveFilm Productions'),
('Une Dernier interdit', 'Un héros solitaire défie les lois de la réalité.', 'Studio du Rire'),
('Un Dernier du désert', 'Un détective tourmenté affronte ses peurs.', 'Cinéstorm'),
('Les Choc de l’oubli', 'Un héros solitaire se bat contre une force obscure.', 'Dreamlight'),
('La Cri de l’oubli', 'Une équipe improbable affronte ses peurs.', 'Dreamlight'),
('Sur Trésor éternel', 'Une jeune fille curieuse affronte ses peurs.', 'Mythic Entertainment'),
('Sous Ombre de l’oubli', 'Un mystère inexpliqué réveille une légende ancienne.', 'Dreamlight'),
('La Éclat céleste', 'Un voyage temporel doit sauver le monde.', 'Mythic Entertainment'),
('Au-delà Cri interdit', 'Un détective tourmenté affronte ses peurs.', 'Flashbox Films'),
('Au-delà Dernier mystérieux', 'Un détective tourmenté se bat contre une force obscure.', 'Studio du Rire'),
('Le Ombre de l’oubli', 'Un robot en fuite cherche la vérité.', 'Studio du Rire'),
('Sur Rêve mystérieux', 'Une équipe improbable tente de changer le destin.', 'LoveFilm Productions'),
('Les Ombre éternel', 'Un voyage temporel réveille une légende ancienne.', 'Dreamlight'),
('Sous Dernier du Temps', 'Un héros solitaire explore l’inconnu.', 'Star Studios'),
('Sous Dernier de l’oubli', 'Une jeune fille curieuse défie les lois de la réalité.', 'Dreamlight'),
('La Cri des Abysses', 'Une guerre imminente cherche la vérité.', 'Émotion Pictures'),
('Dans Éclat des Abysses', 'Une jeune fille curieuse réveille une légende ancienne.', 'Darkline Studios'),
('Au-delà Dernier du Temps', 'Un détective tourmenté réveille une légende ancienne.', 'LoveFilm Productions'),
('Une Secret interdit', 'Un héros solitaire doit sauver le monde.', 'LoveFilm Productions'),
('Le Dernier de glace', 'Un détective tourmenté défie les lois de la réalité.', 'Nova Films'),
('Au-delà Choc de glace', 'Un mystère inexpliqué explore l’inconnu.', 'Star Studios'),
('Vers Voyage du désert', 'Un mystère inexpliqué tente de changer le destin.', 'Studio du Rire'),
('Un Éclat du désert', 'Une équipe improbable affronte ses peurs.', 'Flashbox Films'),
('Au-delà Éclat céleste', 'Une jeune fille curieuse découvre un secret enfoui.', 'Dreamlight'),
('Sur Trésor fantôme', 'Un mystère inexpliqué découvre un secret enfoui.', 'Flashbox Films'),
('Une Souffle de l’oubli', 'Un détective tourmenté défie les lois de la réalité.', 'Studio du Rire'),
('Vers Éclat fantôme', 'Un voyage temporel réveille une légende ancienne.', 'Star Studios'),
('La Secret de l’oubli', 'Un détective tourmenté cherche la vérité.', 'Nova Films'),
('Dans Souffle de glace', 'Un mystère inexpliqué explore l’inconnu.', 'Studio du Rire'),
('Dans Dernier des Abysses', 'Un mystère inexpliqué explore l’inconnu.', 'Studio du Rire'),
('Une Choc des Abysses', 'Une équipe improbable explore l’inconnu.', 'Cinéstorm'),
('Sous Choc du désert', 'Une ancienne prophétie défie les lois de la réalité.', 'Darkline Studios'),
('Sous Souffle du Temps', 'Un mystère inexpliqué défie les lois de la réalité.', 'Flashbox Films'),
('Sur Ombre interdit', 'Une équipe improbable remonte le temps.', 'Darkline Studios'),
('Dans Dernier de glace', 'Un héros solitaire doit sauver le monde.', 'Flashbox Films')";

$pdo->exec($sql); // Exécution de la requête SQL

?>
